apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: demo-service-tomcat
    servicePort: 8081
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: demo-service-nginx
          servicePort: 8080
      - path: /httpd
        backend:
          serviceName: demo-service-httpd
          servicePort: 8080
